server:
  port: 8080

spring:
  application:
    name: smart-street-light
  profiles:
    include: secret  # 引入密码配置文件（application-secret.yml）
  datasource:
    url: jdbc:postgresql://192.168.100.131:5432/smart-street-light
    username: postgres

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cqu.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.cqu:
      mapper: debug
      service: info
      controller: info

# ==================== MQTT 配置（连接 Docker EMQX） ====================
mqtt:
  broker-url: tcp://192.168.100.131:1883
  client-id: smart-light-server