spring:
  datasource:
    password: 123456

jwt:
  secret-key: the_secret_key_of_smart_street_light

llm:
  api-key: your-api-key-here
  base-url: https://api.openai.com
  model: gpt-4o-mini
  embedding-model: text-embedding-3-small
  top-k: 3

mqtt:
  username: admin
  password: 123456